// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa65pn93vXeyjKPqsxMv9xdPtZ5ZRleJw',
    appId: '1:91151508909:web:f3defc86bd414b5a53ad24',
    messagingSenderId: '91151508909',
    projectId: 'elearning-cf8c1',
    authDomain: 'elearning-cf8c1.firebaseapp.com',
    storageBucket: 'elearning-cf8c1.appspot.com',
    measurementId: 'G-639PE3MTT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkcnSpXj9ZGbDBUwFRyV9jt5e1UwuaD9U',
    appId: '1:91151508909:android:a02695fb9793bb8653ad24',
    messagingSenderId: '91151508909',
    projectId: 'elearning-cf8c1',
    storageBucket: 'elearning-cf8c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYMK5vg-33W-Ukrt0MlTf2uVcHaXpMp74',
    appId: '1:91151508909:ios:4a32672a1a6ab8d753ad24',
    messagingSenderId: '91151508909',
    projectId: 'elearning-cf8c1',
    storageBucket: 'elearning-cf8c1.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFormatiom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYMK5vg-33W-Ukrt0MlTf2uVcHaXpMp74',
    appId: '1:91151508909:ios:03f3a994f1665b6453ad24',
    messagingSenderId: '91151508909',
    projectId: 'elearning-cf8c1',
    storageBucket: 'elearning-cf8c1.appspot.com',
    iosBundleId: 'com.example.flutterApplicationFormatiom.RunnerTests',
  );
}
